version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./dbdata:/app/app/data  #  Persist database data (SQLite)
    restart: always
    environment:
      - TZ=UTC

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes-api-frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
