# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes-api-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notes-api-frontend
    ports:
      - "3000:3000"
    restart: always
